### ISSUE TITLE
level up effect

### ISSUE THREAD

**Issue by madtomic** [games647/McCombatLevel#17]
I haven't been able to get this feature to work. Can you check it out for me?

effect:
    lightning: true
    sound:
        # set this empty in order to disable it
        type: 'LEVEL_UP'
        pitch: 0.1
        volume: 1

When a player gain a combat level. no lightning and it seems to me the mcmmo default level up event might taken over this?

**Comment by games647** [comment]
Enough permissions?

**Comment by madtomic** [comment]
There is an effect permission ?

**Comment by games647** [comment]
Yes plugin name in lowercase and '.effect'

**Comment by madtomic** [comment]
Ok, that would explains it. ☺️

**Comment by games647** [comment]
If it is fixed, could you close it?

**Comment by madtomic** [comment]
I'm late but thanks for closing this.
