### ISSUE TITLE
calculation errors?

### ISSUE THREAD

**Issue by madtomic** [games647/McCombatLevel#18]
For example:

formula: 'Math.round((acrobatics + alchemy + archery + axes + excavation + fishing + herbalism + mining + repair + swords + taming + unarmed + woodcutting) / 5)'

This would mean that any 5 combine skill level = 1 combat level?

I found out when you hit 3, you would get combat level 1.
8 = combat level 2
13 = combat level 3
etc.

Can please you look into this?

**Comment by madtomic** [comment]
Any news on this?

**Comment by games647** [comment]
Do you have Javascript enabled?

**Comment by madtomic** [comment]
formula: '(acrobatics + alchemy + archery + axes + excavation + fishing + herbalism + mining + repair + swords + taming + unarmed + woodcutting) / 5'

So is this what you mean?

**Comment by games647** [comment]
yes

**Comment by madtomic** [comment]
Thank you !
