### ISSUE TITLE
command to list players and their levels?

### ISSUE THREAD

**Issue by madtomic** [games647/McCombatLevel#19]
Do you think you can add a command to list players and their levels?

**Comment by games647** [comment]
Do you mean a ordered ranking?

**Comment by madtomic** [comment]
Yes, sorry for delay response.

**Comment by madtomic** [comment]
I hope you will add this sometime. =)

**Comment by madtomic** [comment]
Do you think you could add permission for this as well.

**Comment by games647** [comment]
Yes, of course.

**Comment by games647** [comment]
It was very much work to do.

**Comment by games647** [comment]
>Do you think you could add permission for this as well.

The permission is: mccombatlevel.rankingcommand
