### ISSUE TITLE
custom effect

### ISSUE THREAD

**Issue by madtomic** [games647/McCombatLevel#22]
instead of lightning, can you make the effect custom-able?

This effect would only fire when someone levels up but not when they first log on the server.

**Comment by games647** [comment]
So there are also effects on the first log in?

**Comment by madtomic** [comment]
yes, as of now, it give player effects when they first log in like they would when they leveled up.

**Comment by madtomic** [comment]
Yes, this is not resolved yet.

**Comment by games647** [comment]
I cannot reproduce this issue. Are you sure you used the latest version.
