### ISSUE TITLE
Server wide broadcast of player level up

### ISSUE THREAD

**Issue by madtomic** [games647/McCombatLevel#23]
I think level up messages are set to player only. If you would add in server wide broadcast of player whom levels up would be awesome! Thanks!

**Comment by madtomic** [comment]
I forgot to add, this is not for the player whom leveled up. It's for other to see. Each player should still get their own leveled up message.

#configurable message for broadcast leveled up message

**Comment by games647** [comment]
But the player shouldn't receive the broadcast message?

**Comment by madtomic** [comment]
Players should receive the broadcast message. I just tested the last commit. The level up message are for players only. Can you please add another message for broadcast? 

Player whom level only gets the player message and others would get the broadcast message. They should not get both message.

**Comment by madtomic** [comment]
Any update on this? =)
