### ISSUE TITLE
log in message

### ISSUE THREAD

**Issue by madtomic** [games647/McCombatLevel#24]
Players are still getting level up messages when they log in. It don't matter what level they have before or after. Please fix this.

Also, can you please add a check so it would not show level up when player is only level 0 or new players. New players, are greeted with level up message when they first log in to the server.

Thank you!

**Comment by games647** [comment]
#22

**Comment by madtomic** [comment]
Yes, I am aware of this. I reported before. I think you try to fix it commit but still shows up on log in.
