### ISSUE TITLE
bug with tag_level

### ISSUE THREAD

**Issue by madtomic** [games647/McCombatLevel#25]
Unless you are OP, You can't see the tag_level above your player's head.

McCombatLevel 1.9

**Comment by games647** [comment]
Do you gave the players the permission to see it?

**Comment by madtomic** [comment]
1.8 don't use permission, so unless you changed this in 1.9 then I need to add permission

**Comment by games647** [comment]
It's playername.showLevelTag.

I change it to pluginName.showLevelTag
