### ISSUE TITLE
Default minimum level

### ISSUE THREAD

**Issue by madtomic** [games647/McCombatLevel#26]
Can you add a way to set a default level for all players in config.yml

default_combatlevel: 1

This is for all player joining the server with the minimum combat level for the first time.
The mccombatlevel is added after this minimum level.

**Comment by madtomic** [comment]
not needed since you decline to add https://github.com/games647/McCombatLevel/issues/28

**Comment by games647** [comment]
That was just for the command

**Comment by madtomic** [comment]
Ok, I guess can still use a default combatlevel.

**Comment by games647** [comment]
I thought about it. I think you could just add the min level to the formula and you will get the same result.
