### ISSUE TITLE
Particle effects

### ISSUE THREAD

**Issue by madtomic** [games647/McCombatLevel#27]
Option to set desire effect in config.yml

**Comment by games647** [comment]
Could you describe it more?

**Comment by madtomic** [comment]
What I mean is to use this.

http://minecraft.gamepedia.com/Particles

Let player set the effect in the config.yml

**Comment by games647** [comment]
Ah ok, so particle effects.

**Comment by madtomic** [comment]
Yes, this is for when a player leveled up.
