### ISSUE TITLE
Null Error

### ISSUE THREAD

**Issue by madtomic** [games647/McCombatLevel#31]
Using mcMMO 1.5.04-SNAPSHOT-b82 + McCombatLevel 2.0 + ItemControl 1.0

I included this for you to review as ItemControl has no issue. The Null is from McCombatLevel

ItemControl
Download: https://www.dropbox.com/s/w1uw04hj1dsjdto/ItemControl.jar?dl=0
Source: https://github.com/EcMiner/ItemControl

I get this null error from mcCombatLevel
http://pastebin.com/xZarxPxx

This error started after mcmmo 1.5.01+

**Comment by games647** [comment]
It's a different plugin:

>me.ecminer.itemcontrol.listeners.LevelListener.onPlayerCombatLevelCha
nge

**Comment by madtomic** [comment]
Yes, we look at the source for both itemcontrol  and mcmmo and it all leads to mccombatlevel.

**Comment by games647** [comment]
Why does the plugin [this](https://github.com/EcMiner/ItemControl/blob/master/src/me/ecminer/itemcontrol/listeners/LevelListener.java#L48)?

**Comment by madtomic** [comment]
As itemcontrol uses mccombatlevel as API for the combatlevel events.
What the plugin does it it limited what tools, armor weapons a player can use based on mccombatlevel.

**Comment by games647** [comment]
But the plugin shouldn't call the update method. McCombatLevel already does that.

And according to the stacktrace, the error happens in line 49 which is the access to data collection within ItemControl.

**Comment by madtomic** [comment]
Sigh, I wished EcMiner could help. Do you think you could help me fix this? I had been through like 4 other devs and no one is able to fix this and I hate not having mccombatlevel on the server as it's my oldest plugin and everyone loves it.

**Comment by madtomic** [comment]
One more thing, the source on itemcontrol isn't updated.

the original issue is from this line.

oldLevel.put(player.getName(), plugin.getMcCombatLevel().getCombatLevel(player));

**Comment by madtomic** [comment]
And that's because McCombatLevel cache doesn't contain the player for some reason

**Comment by games647** [comment]
Did you reloaded the server?

**Comment by madtomic** [comment]
Yes, I had and the error still comes up.

**Comment by games647** [comment]
Try a normal startup.

**Comment by madtomic** [comment]
normal startup as in?

**Comment by games647** [comment]
Restart

**Comment by madtomic** [comment]
I had, I created many fresh install for this tests and the error still comes up when someone gain a level and the error comes up.

**Comment by games647** [comment]
I checked it. It's the fault of ItemControl. The account isn't loaded at the time it tries to add it to the collection.

**Comment by madtomic** [comment]
So, this is why it breaks after mcmmo 1.5.01, it changes when the player data is loaded.

**Comment by games647** [comment]
It looks like the author is inactive. I could write a pull request for the project.
