### ISSUE TITLE
Does not work for 1.6.4

### ISSUE THREAD

**Issue by Zilacon** [games647/McCombatLevel#4]
Everyones level shows as 0. The plugin starts, the tags are shown (Prefix isn't compatible with other plugins so it does not display, i disabled this because of that) but everyone is lvl 0.

Even for people who have a total of 1000+ in levels on mcmmo are still 0.

I am running MCMMO: [mcMMO] Running version 1.4.08-b3544
Server: MCPC+ 1.6.4 Build 272
McCombatLVL: 1.7.1

Oh and my MCMMO is storing data on a MYSQL database. Not sure if that affects anything.

**Comment by games647** [comment]
Did you see any errors in the log? Is the MySQL database localhosted? 

You can try to manually edit the mcMMO stats in order to trigger a update. If it's still 0, then there have to be something wrong with the calculation process.

**Comment by Zilacon** [comment]
No errors, besides the combat lvl being 0 nothing is wrong with the plugin.
And yes the mysql database server is on the same dedicated server as the minecraft servers.

**Comment by games647** [comment]
Even no errors on startup?

**Comment by Zilacon** [comment]
Checked my logs when i put the plugin on the server, nothing.

**Comment by Zilacon** [comment]
Wiping my logs and restarting server to double check.

**Comment by games647** [comment]
And /level shows also 0?

**Comment by Zilacon** [comment]
2015-03-30 01:20:05 [INFO] [McCombatLevel] Loading McCombatLevel v1.7.1
Is the only thing in the logs.

And is that a command from your plugin? Cause i am not on the server, getting ready for bed actually. Just looking at it from the console at the moment.

**Comment by games647** [comment]
You can call it from the console with: /level <player>

**Comment by Zilacon** [comment]
Nope i cant, gotta login and do it. Empty server so i cant type a player in. Its late no ones on at this time.

**Comment by games647** [comment]
Okay then good night.

**Comment by Zilacon** [comment]
Im logging in, gimme a minute modpacks take forever on AMD cpus, dont know why.

**Comment by Zilacon** [comment]
Shows "Combat Level: 1" (I dont play much) but i asked my players when i was on before i made this if it said 0 for me and they said yes.

**Comment by games647** [comment]
Could you send me your config, please?

**Comment by Zilacon** [comment]
# True by default, this is the prefix to the left of the name in chat.
enable_prefix: false

#  True by default, this is the level that appears above the player's head
enable_tag_level: true

# "&aCombat" by default, this is the text that appears after the level above the player's head
tag_name: '&aCombat LVL'

# GOLD by default, change the color of the brackets in the level prefix
prefix_bracket_color: GOLD

# DARK_GREEN by default, change the color of the level in the prefix
prefix_level_color: DARK_GREEN

# Math.round((unarmed + swords + axes + archery + .25 * acrobatics + .25 * taming) / 45) by default
# How the combat is calculated
formula: 'Math.round((unarmed + swords + axes + archery + .25 * acrobatics + .25 * taming) / 45)'

**Comment by games647** [comment]
Thank you, I guess I found the problem. I'll test a bit.

**Comment by Zilacon** [comment]
What do you think the problem is?

**Comment by games647** [comment]
The mcMMO stats are loaded async (separate thread/task). Sadly mcMMO doesn't notify if the loading is finished, so McCombatLevel waits three seconds, but it could possible happen that three seconds aren't enough and the loading process still runs.

**Comment by Zilacon** [comment]
If your mentioning threats i suppose i should mention my server is running TickThreading.
https://github.com/nallar/TickThreading

Which runs the entire server on multiple threads. But so far i have not had any problems with any plugins while using this.

**Comment by games647** [comment]
That's a good point. I'll test it.

**Comment by Zilacon** [comment]
Thanks. Let me know what you find out.
Going to hop into bed now.

**Comment by Zilacon** [comment]
Oh! I left the server and it errored!
Heres the error: http://pastie.org/pastes/10062317/text

Hope it helps.

**Comment by games647** [comment]
That was very helpful

**Comment by Zilacon** [comment]
Could you make a release on github so i can put this on my server?

**Comment by games647** [comment]
Here you go:

https://github.com/games647/McCombatLevel/releases/tag/1.7.2

**Comment by Zilacon** [comment]
Thank you very much :D
I appreciate your quick response on the fix, most devs simply ignore me.

**Comment by Zilacon** [comment]
It works! Thank you!
