### ISSUE TITLE
Title not displaying properly

### ISSUE THREAD

**Issue by BotteledCacti** [games647/McCombatLevel#42]
Hi! First I just want to say that McMMO Combat Level is an incredible plugin! It's so simple but still does so much, thank you! But I seem to have a problem, the actual levels (The bar under the name) aren't always showing, It sometimes is but most of the time only the name is visible. Do you have any idea what could cause this?

**Comment by games647** [comment]
Other scoreboard plugins could conflict with this plugin.

**Comment by BotteledCacti** [comment]
Alright, so I guess the McMMO Scoreboard is conflicting then?

2017-12-15 17:03 GMT+01:00 games647 <notifications@github.com>:

**Comment by games647** [comment]
Yes for example
