### ISSUE TITLE
Please fix PlaceholderAPI support

### ISSUE THREAD

**Issue by madtomic** [games647/McCombatLevel#43]
Can you please help fix the error: https://pastebin.com/eN8T7rXg

This is using the latest build. v2.1.1

Ref: https://github.com/pixar02/McCombatLevel-Expansion

FeatherBoard API
https://www.spigotmc.org/wiki/featherboard-api/

**Comment by madtomic** [comment]
I am confused, as according to your last note in regards to this. It was revert back to 2.0.1 method so this breaks it now?

**Comment by games647** [comment]
The other plugin just have to be updated. That's it.
