### ISSUE TITLE
MVdWPlaceholderAPI

### ISSUE THREAD

**Issue by madtomic** [games647/McCombatLevel#44]
if (getServer().getPluginManager().isPluginEnabled("MVdWPlaceholderAPI")) {
            PlaceholderAPI.registerPlaceholder(this, "combat_level", replaceEvent -> {
                if (!replaceEvent.isOnline()) {
                    return "Player not online";
                }

                Player player = replaceEvent.getPlayer();
                OptionalInt combatLevel = getLevel(player);
                if (combatLevel.isPresent()) {
                    return Integer.toString(combatLevel.getAsInt());
                }

                return "Level not loaded";
            });
        }

I just notice this. Should I be using this instead of the paperholderapi?

**Comment by madtomic** [comment]
When using combat_level, I only get Level not loaded message for the variable.

**Comment by games647** [comment]
The reason is your plugin that uses those data is requesting the combat level to earlier at the moment it's not loaded. As I said in the other ticket it's not possible to load it earlier because mcMMO provides no event for it.
