### ISSUE TITLE
Using the latest build of MCMMO, combatlevel is not working

### ISSUE THREAD

**Issue by madtomic** [games647/McCombatLevel#45]
Greeting, I just tested the new 2.2 build with the latest build of MCMMO and it is not working.
You can get the latest MCMMO here.
https://popicraft.net/jenkins/job/mcMMO/

Thank you,

**Comment by games647** [comment]
I guess you meant 2.1.2?

**Comment by M2VC** [comment]
Having this issue too? Any ETA on a fix?

**Comment by games647** [comment]
@M2VC Same question which version do you run?

**Comment by madtomic** [comment]
I am referring to the latest version.

**Comment by games647** [comment]
Should be fixed now.
