### ISSUE TITLE
Build Failure on the lastest source

### ISSUE THREAD

**Issue by madtomic** [games647/McCombatLevel#46]
Results :

Tests in error:
  testScript(com.gmail.mrphpfan.CalculationTest)

Tests run: 2, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:26 min
[INFO] Finished at: 2018-05-08T22:46:29-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project mccombatlevel: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\madtomic\Desktop\mvn\new\McCombatLevel-master\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by games647** [comment]
Just append "-DskipTests=true" or download a version from the dev build link.

**Comment by madtomic** [comment]
Thank you
