### ISSUE TITLE
When issued /stop in console

### ISSUE THREAD

**Issue by madtomic** [games647/McCombatLevel#6]
This error comes up.

http://pastebin.com/ZgqaeSBt

**Comment by games647** [comment]
That's fixed in [dad8b16](https://github.com/games647/McCombatLevel/commit/dad8b1604607449354897f2df6f92d588cf392e1) too. (See [here](https://github.com/games647/McCombatLevel/blob/master/src/main/java/com/gmail/mrphpfan/mccombatlevel/McCombatLevel.java#L214))
