### ISSUE TITLE
NPC Combat Level

### ISSUE THREAD

**Issue by madtomic** [games647/McCombatLevel#7]
NPC Combat Level

After reading some of the comments on the bukkit page. I was wondering about the same thing.

Would it be possible to assign a custom combat level to them?

I know, as of now. They are just names, no combat level. If you change type to villager from a player. However, player are show 0 Combat Level this can be fix by changing the skills it has in mcMMO.

Regards,
madtomic

**Comment by games647** [comment]
As NPCs are handled as non-players in the server API, they don't have any mcMMO skills and so are ignored by McCombatLevel. They don't even get the value 0. The client gives every player either the known value or 0 as default for non existing information,

So it would be only possible to give them either fake values or lookup for existing players in the mcMMO database that have the same name.
